server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/inventory
    username: inventory
    password: inventory

observability:
  service-name: shash.demo-inventory-service
  otlp-endpoint: http://localhost:4317
