server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://inventory-postgres:5432/inventory
    username: inventory
    password: inventory

observability:
  service-name: shash.demo-inventory-service
  otlp-endpoint: http://otel-collector:4317
