apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: personal-workspace
  labels:
    app: orders-service
spec:
  selector:
    app: orders-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: personal-workspace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: shashtaazaa/orders-service:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://orders-postgres:5432/orders
            - name: SPRING_DATASOURCE_USERNAME
              value: orders
            - name: SPRING_DATASOURCE_PASSWORD
              value: orders
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4317
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=orders-service,service.namespace=observability-demo,deployment.environment=dev
            - name: INVENTORY_BASE_URL
              value: http://inventory-service:8080
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /orders/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /orders/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
