apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: personal-workspace
  labels:
    app: orders-service
spec:
  selector:
    app: orders-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: personal-workspace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: shashtaazaa/orders-service:1.11.0-groundcover
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://orders-postgres:5432/orders
            - name: SPRING_DATASOURCE_USERNAME
              value: orders
            - name: SPRING_DATASOURCE_PASSWORD
              value: orders
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4317
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
              value: http://otel-collector:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: INVENTORY_BASE_URL
              value: http://inventory-service:8080
            - name: OTEL_INSTRUMENTATION_LOGGING_EXPERIMENTAL_ENABLED
              value: "true"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /orders/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /orders/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
