server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: orders-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://orders-postgres:5432/orders}
    username: ${DATABASE_USERNAME:orders}
    password: ${DATABASE_PASSWORD:orders}
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    connect-retries: 10
observability:
  enabled: true
  service-name: shash.demo-orders-service
  sampling-probability: 1.0
  exporter: otlp
  otlp-endpoint: ${OTLP_ENDPOINT:http://otel-collector:4317}
  # OTLP logging configuration
  otlp-logs-endpoint: ${OTLP_LOGS_ENDPOINT:http://otel-collector:4317}
logging:
  pattern:
    console: "%d %-5level [%thread] %logger - %msg trace_id=%X{trace_id} span_id=%X{span_id}%n"
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

inventory:
  base-url: ${INVENTORY_BASE_URL:http://inventory-service:8080}
