server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://orders-postgres:5432/orders
    username: orders
    password: orders

observability:
  otlp-endpoint: http://otel-collector:4317

inventory:
  base-url: http://inventory-service:8080
